### ISSUE TITLE
How to compile it?

### ISSUE THREAD

**Issue by geaplanet** [rilian-la-te/vala-panel-appmenu#93]
Hi, I'm not familiar with Vala, could someone write briefly how it compiles?

I tried "cmake ." but it gives me:

> CMake Error at CMakeLists.txt:13 (include):
>   include could not find load file:
> 
>     GitVersion
> 
> CMake Error at CMakeLists.txt:14 (determine_fallback_version):
>   Unknown CMake command "determine_fallback_version".
> 

Thanks in advance.

**Comment by imccausl** [comment]
This is a git error because the repository has sub modules. You have to type git submodule init && git submodule update to download the submodules. Then try cmake again.

**Comment by geaplanet** [comment]
Thanks.
Now I got this, but It doesn't show the name of the missing package:

> cmake .
> -- The C compiler identification is GNU 6.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Looking for RPMTools... - rpmbuild NOT FOUND
> -- Found Vala: /usr/bin/valac  
> -- checking for a minimum Vala version of 0.24
> --   found Vala, version 0.32.1
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
> CMake Error at /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:424 (message):
>   A required package was not found
> Call Stack (most recent call first):
>   /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
>   CMakeLists.txt:60 (pkg_check_modules)
> 
> 
> -- Configuring incomplete, errors occurred!
>

**Comment by rilian-la-te** [comment]
Just look to CMakeLists.txt and install all packages (and its dev, if you
do not use good distro)

**Comment by geaplanet** [comment]
I looked line by line CMakeList and...I give up, I don't know what else I can install :-/

My system is Debian testing.

**Comment by rilian-la-te** [comment]
What are you have installed?

**Comment by geaplanet** [comment]
autoconf (2.69-10)
automake (1:1.15-5)
autopoint (0.19.8.1-1)
autotools-dev (20160430.1)
binfmt-support (2.1.6-1)
budgie-core-dev (10.2.8-1)
build-essential (12.2)
ca-certificates-mono (4.6.1.3+dfsg-5)
cli-common (0.9+nmu1)
cmake (3.6.2-2)
cmake-data (3.6.2-2)
debhelper (10.2.2)
dh-autoreconf (12)
dh-strip-nondeterminism (0.028-1)
g++ (4:6.1.1-1)
g++-6 (6.2.0-11)
gettext (0.19.8.1-1)
gir1.2-atspi-2.0 (2.22.0-3)
gir1.2-budgie-desktop-1.0 (10.2.8-1)
gir1.2-gtk-2.0 (2.24.31-22deepin)
gir1.2-wnck-1.0 (2.30.7-5)
gir1.2-wnck-3.0 (3.20.1-2)
gobject-introspection (1.50.0-1)
intltool-debian (0.35.0+20060710.4)
libarchive-zip-perl (1.59-1)
libatk1.0-dev (2.22.0-1)
libatk-bridge2.0-dev (2.22.0-1)
libatspi2.0-dev (2.22.0-3)
libbamf0 (0.2.118-1.3)
libbamf-dev (0.2.118-1.3)
libbudgie-plugin0 (10.2.8-1)
libbudgietheme0 (10.2.8-1)
libcairo2-dev (1.14.6-1.1)
libcairo-script-interpreter2 (1.14.6-1.1)
libdbus-1-dev (1.10.12-1)
libdbus-glib-1-dev (0.108-1)
libdrm-dev (2.4.71-1)
libegl1-mesa-dev (12.0.3-4)
libepoxy-dev (1.3.1-1)
libexpat1-dev (2.2.0-1)
libffi-dev (3.2.1-6)
libfile-stripnondeterminism-perl (0.028-1)
libfontconfig1-dev (2.11.1-1.1)
libfreetype6-dev (2.6.5-5.0)
libgdk-pixbuf2.0-dev (2.36.0-1)
libgirepository1.0-dev (1.50.0-1)
libglib2.0-cil (2.12.10-6)
libglib2.0-cil-dev (2.12.10-6)
libglib3.0-cil (2.99.3-2)
libglib3.0-cil-dev (2.99.3-2)
libglibmm-2.4-dev (2.50.0-1)
libgraphite2-dev (1.3.8-1)
libgtk2.0-dev (2.24.31-22deepin)
libgtk-3-dev (3.22.2-1)
libharfbuzz-dev (1.2.7-1+b1)
libharfbuzz-gobject0 (1.2.7-1+b1)
libice-dev (2:1.0.9-1+b1)
libjsoncpp1 (1.7.4-3)
libltdl-dev (2.4.6-2)
libmail-sendmail-perl (0.79.16-1)
libpango1.0-dev (1.40.3-3)
libpeas-dev (1.20.0-1)
libpixman-1-dev (0.34.0-1)
libpng-dev (1.6.26-1)
libpng-tools (1.6.26-1)
libpthread-stubs0-dev (0.3-4)
libraven0 (10.2.8-1)
librpm3 (4.12.0.1+dfsg1-6)
librpmbuild3 (4.12.0.1+dfsg1-6)
librpmio3 (4.12.0.1+dfsg1-6)
libsigc++-2.0-dev (2.10.0-1)
libsm-dev (2:1.2.2-1+b1)
libstartup-notification0-dev (0.12-4)
libsys-hostname-long-perl (1.5-1)
libtool (2.4.6-2)
libvala-0.32-0 (0.32.1-1)
libvala-0.32-dev (0.32.1-1)
libwayland-bin (1.11.0-2)
libwayland-dev (1.11.0-2)
libwnck-3-dev (3.20.1-2)
libwnck-dev (2.30.7-5)
libx11-dev (2:1.6.3-1)
libx11-doc (2:1.6.3-1)
libx11-xcb-dev (2:1.6.3-1)
libxau-dev (1:1.0.8-1)
libxcb1-dev (1.12-1)
libxcb-dri2-0-dev (1.12-1)
libxcb-dri3-dev (1.12-1)
libxcb-glx0-dev (1.12-1)
libxcb-present-dev (1.12-1)
libxcb-randr0-dev (1.12-1)
libxcb-render0-dev (1.12-1)
libxcb-shape0-dev (1.12-1)
libxcb-shm0-dev (1.12-1)
libxcb-sync-dev (1.12-1)
libxcb-xfixes0-dev (1.12-1)
libxcomposite-dev (1:0.4.4-1)
libxcursor-dev (1:1.1.14-1+b1)
libxdamage-dev (1:1.1.4-2+b1)
libxdmcp-dev (1:1.1.2-1.1)
libxext-dev (2:1.3.3-1)
libxfce4panel-2.0-dev (4.12.1-1)
libxfconf-0-dev (4.12.0-3)
libxfixes-dev (1:5.0.2-1)
libxft-dev (2.3.2-1)
libxi-dev (2:1.7.6-1)
libxinerama-dev (2:1.1.3-1+b1)
libxkbcommon-dev (0.6.1-1)
libxml2-utils (2.9.4+dfsg1-2.1)
libxrandr-dev (2:1.5.0-1)
libxrender-dev (1:0.9.9-2)
libxres-dev (2:1.0.7-1+b1)
libxshmfence-dev (1.2-1)
libxtst-dev (2:1.2.2-1+b1)
libxxf86vm-dev (1:1.1.4-1)
m4 (1.4.17-5)
po-debconf (1.0.20)
python3-mako (1.0.4+ds1-2)
python3-markupsafe (0.23-3)
rpm-common (4.12.0.1+dfsg1-6)
valac (0.32.1-1)
valac-0.32-vapi (0.32.1-1)
wayland-protocols (1.7-1)
x11proto-composite-dev (1:0.4.2-2)
x11proto-core-dev (7.0.31-1)
x11proto-damage-dev (1:1.2.1-2)
x11proto-dri2-dev (2.8-2)
x11proto-fixes-dev (1:5.0-2)
x11proto-gl-dev (1.4.17-1)
x11proto-input-dev (2.3.2-1)
x11proto-kb-dev (1.0.7-1)
x11proto-randr-dev (1.5.0-1)
x11proto-record-dev (1.14.2-1)
x11proto-render-dev (2:0.11.1-2)
x11proto-resource-dev (1.2.0-3)
x11proto-xext-dev (7.3.0-1)
x11proto-xf86vidmode-dev (2.3.1-2)
x11proto-xinerama-dev (1.2.1-2)
xorg-sgml-doctools (1:1.11-1)
xtrans-dev (1.3.5-1)

**Comment by rilian-la-te** [comment]
You need libbamf

**Comment by geaplanet** [comment]
Ok, libbamf0 (0.2.118-1.3) and libbamf-dev (0.2.118-1.3) were installed, but not libbamf3-dev. Now cmake says this:

> cmake .
> -- checking for a minimum Vala version of 0.24
> --   found Vala, version 0.32.1
> -- Checking for modules 'vala-panel;libpeas-1.0'
> --   No package 'vala-panel' found
> -- Checking for module 'vala-panel>=0.3.50'
> --   
> -- checking for a minimum Vala version of 0.24
> --   found Vala, version 0.32.1
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/minino/Downloads/vala-panel-appmenu

Thanks for your patience.

**Comment by rilian-la-te** [comment]
Closing as fixed

**Comment by gcvl** [comment]
Hi,
I'm encountering the same issue in 0.5.2 and master:

_CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

    GitVersion


CMake Error at CMakeLists.txt:14 (determine_fallback_version):
  Unknown CMake command "determine_fallback_version".


-- Configuring incomplete, errors occurred!
See also "/home/giannino/Scaricati/vala-panel-appmenu-master/CMakeFiles/CMakeOutput.log"._

0.5.1 works fine instead, cmakes and installs!
I'm on Xubuntu 16.04.

**Comment by rilian-la-te** [comment]
did you done ```git submodule init && git submodule update```?

**Comment by gcvl** [comment]
Hi,
Yes, I tried and it gave me some error about .git noit being a valid repository...

**Comment by gcvl** [comment]
I had to type git init first of all, then git submodule init and git submodule update but in the end it keeps complaining about GitVersion.

**Comment by rilian-la-te** [comment]
How are you downloaded a source?

**Comment by gcvl** [comment]
Here's what I just did to make it work:

git clone https://github.com/rilian-la-te/vala-panel-appmenu.git
cd ~/vala-panel-appmenu
git init
git submodule init
git submodule update
cmake .
make
sudo make install

**Comment by rilian-la-te** [comment]
```git init``` is wrong, you resetted a repository.

**Comment by gcvl** [comment]
Indeed, but here it was the only way to get it working, I don't know why...

**Comment by rilian-la-te** [comment]
If you will repeat a sequence without git init, can you show me an error?

**Comment by gcvl** [comment]
If I download the source with git clone it's fine and git init is not needed, just git submodules init and git submodules update will do the trick.

The ZIP file download causes this:

$ cmake .
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

    GitVersion


CMake Error at CMakeLists.txt:14 (determine_fallback_version):
  Unknown CMake command "determine_fallback_version".


-- Configuring incomplete, errors occurred!
See also "/home/giannino/Scaricati/vala-panel-appmenu-master/CMakeFiles/CMakeOutput.log".

$ git submodule init
fatal: Not a git repository (or any of the parent directories): .git
$ git submodule update
fatal: Not a git repository (or any of the parent directories): .git

Here if I type git init it will not give me the above errors but it eventually fails and complains about GitVersion.
So one has to use git clone only (or tar.gz) + git submodules init + git submodules update.

**Comment by rilian-la-te** [comment]
Or use a provided tarball:-) download zip sources is not working

**Comment by nkkollaw** [comment]
Why is it so hard to add an INSTALL file..? So much time wasted by so many people...

**Comment by rilian-la-te** [comment]
But we have README:-) i described installation in it:-)))
Or you like separate file?

**Comment by nkkollaw** [comment]
You don't mention how to install dependencies, you don't mention Git sub modules, you don't mention commands to configure, compile, and install.

There are people all over the internet trying to figure out how to install, while you're the one who knows how to do it and could have saved everyone a lot of suffering by just providing clear instructions.

A separate files would also be nice, the README is very long and install instructions are buried at the bottom.

**Comment by imccausl** [comment]
Are we reading the same document? I’m legitimately confused. What install instructions are buried at the bottom? Git submodules are absolutely mentioned in the context of what to type immediately after cloning the repository. And all of the commands to configure compile and install are quite clearly there, including all of the flags for various compile options.. 

As I see it, the problem with instructions for how to install the dependencies, although a good idea to include, is that it varies from distro to distro. I, for example, have no idea how to install the dependencies for anything other than ubuntu. I’m no wizard, but I figured it out by using ’apt search’.

Having an install script would also be great but it would have to address the various compile options and the different ways of installing dependencies on different distros, otherwise it’s useless. So yeah, it is kind of hard, actually. 

I would suggest though, as a matter of course for a small open source project that the author is devoting his free time to and giving away for free, that instead of asking, apparently combatively, “why is it so hard...” you ask, “how can I help?”

**Comment by nkkollaw** [comment]
> As I see it, the problem with instructions for how to install the dependencies, although a good idea to include, is that it varies from distro to distro.

Probably true, but at least a list?

> that instead of asking, apparently combatively, “why is it so hard...” you ask, “how can I help?”

You're absolutely right and I apologize to the author. I was just pissed off after spending a few hours unable to figure out deps from cryptic cmake errors and it was half of a rant.

ATM I gave up, I can't do it :relieved:

**Comment by imccausl** [comment]
I use ubuntu, and I was previously trying to put together a list of the dependencies in an install script until I realized that it would not be of much help to non-ubuntu people; however, I can suggest that given this list of dependencies,

GLib (>= 2.40.0)
GTK+ (>= 3.12.0)
valac (>= 0.24.0)
libbamf (>=0.5.0)

you need to install the dev portion. So, for example, in ubuntu there is libgtk-3-common and libgtk-3-dev (note that under the dependencies, you need a version of GTK+ that is above 3.12, so you want libgtk-3 not 2). You need to ensure you have libgtk-3-dev installed. Same goes for glib. In ubuntu, the glib packages are under libglib2.0 and you want to ensure you have libglib2.0-dev installed. 

The Valac package is for compiling the whole thing, so that one is easy enough. Ensure the valac library is installed.

Finally, again under Ubuntu you ensure you install libbamf3-2 and libbamf3-dev.

I've installed it with Arch before, but it's been awhile and I don't remember exactly how it worked; however, I think the AUR did most of the heavy-lifting for me.

Again, because how dependencies are packaged changes from distro to distro, it's hard to know what the packages will look like, but the key is to ensure you have the DEV dependencies installed (i.e. those with all the header files and source code belonging to the libraries necessary for compilation), and not just the libraries themselves.

The other key is to ensure that unity-gtk-module is installed because whether or not you are using Ubuntu or unity, the entire appmenu depends on unity-gtk-module to create the global menu, and, as far as bamfdaemon, sometimes this is installed with a separate package, and sometimes it is installed along with libbamf. I believe in Ubuntu, you have to install it separately (sudo apt install bamfdaemon).

99% of the time, if you get a compile error, it is because you don't have one of the dev dependencies installed. I can try to help you out if you are using Ubuntu, otherwise you may want to google for something like 'libgtk3 dev dependencies [my distro]'.

** It's been awhile since I used this project (although I do love it), because I decided to take the plunge into wayland with Ubuntu 17.10 and I don't believe it works with wayland.

**Comment by nkkollaw** [comment]
Thanks, man! I'll give that a try. I'm using elementary OS which is Ubuntu-based, so that should work...

**Comment by imccausl** [comment]
As far as i now you may have trouble getting it to work with elementary’s top panel so you may have to replace that panel (I can’t remember what it is called) with something like xfce-panel or Vala-panel. But we can certainly try to work through the issues.

**Comment by rilian-la-te** [comment]
@imccausl you forgot bamfdaemon, but thanks anyway.
Yes, wayland is not supported now, but you can add support of it, and I will. But it is a difflicult task (because we need window list)

@nkkolaw, on elementary OS you need another panel. Try vala-panel, or xfce4-panel 4.14:-)

**Comment by imccausl** [comment]
@rilian-la-te I didn't forget, but I did bury it in the paragraph about unity-gtk-module :/ oopsie.
